version: "3.8"

  database:
    build: 
       context: ./database
    image: perinity_db
    user: postgres
    environment:
      POSTGRES_USER: perinityuser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: perinity
    ports:
      - "5432:5432" 
    networks:
      - postgres-network
    
  appserver:
    build:
       context: app
       dockerfile: Dockerfile
    image: perinity_app
    user: perinity
    ports:
      - "8080:8080" 
      - "5005:5005"
    networks:
      - postgres-network

networks:
  postgres-network:
        driver: bridge

